hello:
  cmd: echo hello $name
  args: name
  return: text

sum:
  cmd: python ./service/sum.py $a $b
  args:
    - a
    - b
  return: json

upload:
  cmd: python ./service/upload.py $file $files ./saved
  args:
    - file
    - files
  return: json

download:
  cmd: python ./service/download.py $file
  args: file
  return: file

about:
  cmd: python ./service/about.py ./configs/rules_demo.yaml
  args: ~
  return: text

pyversion:
  cmd: python --version
  args: ~
  return: text

cwd:
  cmd: pwd
  args: ~
  return: text